name: Beam Tests

on: ['push', 'pull_request']

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        php: [ 8.4, 8.3, 8.2, 8.1 ]
        laravel: [ 12.*, 11.*, 10.* ]
        dependency-version: [ prefer-stable ]
        include:
          - laravel: 12.*
            testbench: 10.*
          - laravel: 11.*
            testbench: 9.*
          - laravel: 10.*
            testbench: 8.*
        exclude:
          - php: 8.1
            laravel: 11.*
          - php: 8.1
            laravel: 12.*

    name: "PHP: ${{ matrix.php }} / ${{ matrix.os }} / Laravel: ${{ matrix.laravel }}"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, fileinfo
          tools: composer:v2

      - name: Cache composer dependencies
        uses: actions/cache@v3
        with:
          path: $(composer config cache-files-dir)
          key: dependencies-laravel-${{ matrix.laravel }}-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}
          restore-keys: dependencies-laravel-${{ matrix.laravel }}-php-${{ matrix.php }}-composer-

      - name: Install Composer dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench-core:${{ matrix.testbench }}" --no-interaction --no-update
          composer install

      - name: Pint 👨‍🏭
        if: matrix.php == '8.3' && matrix.os == 'ubuntu-latest'
        run: composer test:pint
        env:
          PHP_CS_FIXER_IGNORE_ENV: 1

#      - name: Larastan ⚗️ (temporary disabled)
#        if: matrix.os == 'ubuntu-latest' && matrix.laravel == '11.x'
#        run: composer test:types

      - name: Pest Tests 👨🏻‍🔬
        run: composer test:tests
